# Full documentation: https://gohugo.io/getting-started/configuration/

# (string) The absolute URL (protocol, host, path, and trailing slash) of your published site
# (e.g., https://www.example.org/docs/).
baseURL: 'https://oleksii-khalikov.github.io/'

# (string) A language tag as defined by RFC 5646. This value is used to populate:
# - The <language> element in the embedded RSS template
# - The lang attribute of the <html> element in the embedded alias template
# - The og:locale meta element in the embedded Open Graph template
# When present in the root of the configuration, this value is ignored if one or more language keys exists.
# Please specify this value independently for each language key.
languageCode: 'uk'


# (string) Site title.
title: 'Oleksii Khalikov @GFalcon-UA'


# (string) Default is ap. See Configure Title Case https://gohugo.io/getting-started/configuration/#configure-title-case.
titleCaseStyle: ap


theme: "hello-gfalcon"


# Copyright notice for your site, typically displayed in the footer.
copyright: "All Rights Reserved"


IsMultiLingual: false


# Content without language indicator will default to this language.
defaultContentLanguage: uk


# When building, removes files from destination not found in static directories.
cleanDestinationDir: true


# (bool) Render the default content language in subdir, e.g. content/en/. The site root / will then redirect to /en/.
defaultContentLanguageInSubdir: false


# (bool) Include drafts when building.
# Default is false.
buildDrafts: false


# (bool) Include content already expired.
# Default is false.
buildExpired: false


# (bool) Include content with a future publication date.
# Default is false.
buildFuture: false


# (bool) Whether to capitalize automatic list titles. Applicable to section, taxonomy, and term pages. Default is true.
# You can change the capitalization style in your site configuration to one of ap, chicago, go, firstupper, or none.
capitalizeListTitles: true


# Do not enable this option unless you are creating a serverless site, navigable via the file system.
relativeURLs: false


# (bool) Will disable generation of alias redirects. Note that even if disableAliases is set, the aliases themselves
# are preserved on the page. The motivation with this is to be able to generate 301 redirects in an .htaccess,
# a Netlify _redirects file or similar using a custom output format.
# Default is false.
disableAliases: false


# (bool) Hugo will, by default, inject a generator meta tag in the HTML head on the home page only.
# You can turn it off, but we would really appreciate if you don’t, as this is a good way to watch
# Hugo’s popularity on the rise.
# Default is false.
disableHugoGeneratorInject: false


# (string slice) Disable rendering of the specified page kinds,
# any of 404, home, page, robotstxt, rss, section, sitemap, taxonomy, or term.
disableKinds:
#  - '404'
#  - home
#  - page
#  - robotsTXT
  - RSS
#  - section
#  - sitemap
#  - taxonomy
#  - term


# (bool) Disable automatic live reloading of browser window.
# Default is false.
disableLiveReload: false


# (bool) Do not convert the url/path to lowercase.
# Default is false.
disablePathToLower: false


# (bool) Enable Emoji emoticons support for page content; see the emoji shortcode quick reference guide.
# https://gohugo.io/quick-reference/emojis/
# Default is false.
enableEmoji: true


# (bool) Enable .GitInfo object for each page (if the Hugo site is versioned by Git).
# This will then update the Lastmod parameter for each page using the last git commit date for that content file.
# Default is false.
enableGitInfo: true


# (bool) Show a placeholder instead of the default value or an empty string if a translation is missing.
# Default is false.
enableMissingTranslationPlaceholders: false


# (bool) Enable generation of robots.txt file.
# Default is false.
enableRobotsTXT: true


# (string) The editor to use when creating new content.
# newContentEditor: ""


# (bool) Don’t sync permission mode of files.
# Default is false.
noChmod: false


# (bool) Don’t sync modification time of files.
# Default is false.
noTimes: false


# (int) Default number of elements per page in pagination.
# Default is 10.
paginate: 10


# (string) The path element used during pagination (https://example.org/page/2).
# Default is page.
paginatePath: page


# (bool) Whether to pluralize automatic list titles. Applicable to section pages.
# Default is true.
pluralizeListTitles: true


# (string) When using ref or relref to resolve page links and a link cannot be resolved,
# it will be logged with this log level.
# Valid values are ERROR (default) or WARNING.
# Any ERROR will fail the build (exit -1).
# Default is ERROR.
refLinksErrorLevel: ERROR


# (string) URL to be used as a placeholder when a page reference cannot be found in ref or relref. Is used as-is.
# refLinksNotFoundURL: ""


# (bool) Removes non-spacing marks from composite characters in content paths.
# content/post/hügó.md → https://example.org/post/hugo/
# Default is false.
removePathAccents: true


# (int) Applicable to automatic summaries, the approximate number of words to render
# when calling the Summary method on a Page object.
# Default is 70.
summaryLength: 70


# (string) Timeout for generating page contents, specified as a duration or in seconds.
# Note: this is used to bail out of recursive content generation. You might need to raise this limit if
# your pages are slow to generate (e.g., because they require large image processing or depend on remote contents).
# Default is 30s.
timeout: 30s


# (bool) When enabled, creates URL of the form /filename.html instead of /filename/.
# Default is false.
uglyURLs: true


