baseURL: 'https://oleksii-khalikov.github.io/'
languageCode: 'uk'
title: 'My New Hugo Site'

theme: "hello-4s3ti"
#theme = 'ananke'



copyright: "All Rights Reserved"
IsMultiLingual: false
defaultContentLanguage: uk
