baseURL: 'https://oleksii-khalikov.github.io/'
languageCode: 'uk'
title: 'Oleksii Khalikov @GFalcon-UA'

theme: "hello-gfalcon"

copyright: "All Rights Reserved"
IsMultiLingual: false
defaultContentLanguage: uk
