uk:
  weight: 1
  languageName: "Ukrainian / Українска"
#en:
#  weight: 2
#  languageName: "English"
#  params:
#    backgroundImage: "../assets/4s3tibg.gif"
#pl:
#  weight: 3
#  languageName: "Polish / Polski"
#  params:
#    backgroundImage: "../assets/4s3tibg.gif"
