main:
#  - identifier: "about"
#    name: "Sobre"
#    url: "https://cv.4s3ti.net"
#    weight: 2

  - identifier: "posts"
    name: "Posts"
    url: "/posts"
    weight: 1

#  - identifier: "tools"
#    name: "Ferramentas"
#
#  - identifier: "projects"
#    name: "Projetos"
#    url: "/projects"
#
#  - identifier: "PiVPN"
#    name: "PiVPN"
#    url: "https://pivpn.io"
#    parent: "projects"
#  - identifier: "short"
#    name: "Diminuir Links"
#    url: "https://s.4s3ti.net"
#    parent: "tools"
#  - identifier: "whiteboard"
#    name: "Quadro Branco"
#    parent: "tools"
#    url: "https://wb.4s3ti.net"
#  - identifier: "PrivateBin"
#    name: "PrivateBin"
#    parent: "tools"
#    url: "httls://paste.4s3ti.net"
