defaultTheme: "dark"
author:
  name: "Oleksii Khalikov"
EnableThemeToggle: true
# gitUrl: "https://github.com/4s3ti"
EnableSharingButtons: true
EnableGlobalLanguageMenu: false
backgroundImage: "assets/4s3tibg.gif"
backgroundEffects: true
showPosts: true
tags: true
# hideReadMore: true
ReadMoreText: true
# ReadMore: "foo"
# socialIcons: true
# homeTitle: "Title"
# homeSubtitle: "Subtitle"
fontAwesome:
  KitURL: "https://kit.fontawesome.com/0ed5cec925.js"
ShowReadingTime: true
LastModDisplay: true
portrait:
  path: "https://avatars.githubusercontent.com/u/13604023?v=4"
  alt: "Portrait"
  maxWidth: "50px"
logo:
  logoMark: ">"
  logoText: "$ cd /home/"
  logoHomeLink: "/"
  logoCursorDisabled: false
  logoCursorAnimate: "2s"
  logoCursorColor: "#ffffff"
social:
  - name: "github"
    url: "https://github.com/4s3ti"
  - name: "CV"
    url: "https://cv.4s3ti.net"
    icon: fa-solid fa-terminal
  - name: "youtube"
    url: "https://youtube.com/cfcolaco"
  - name: "twitter"
    url: "https://twitter.com/4s3ti/"
  - name: "instagram"
    url: "https://www.instagram.com/c4colaco/"
  - name: "twitch"
    url: "https://twitch.tv/4s3ti"
  - name: "Buy me a coffee"
    url: "https://www.buymeacoffee.com/4s3ti"
    icon: fa-solid fa-coffee
footer:
  showVersion: true
  socialIcons: true
  author: true
  rss: true
  trademark: true
  copyright: true
  #   topText:  ["Footer Top text"]
  bottomText: [
    "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    "with <a href=\"#\">Hello-friend-4s3ti</a>",
  ]
